server:
  port: 8087 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境

mybatis:
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml


rocketmq:
  name-server: 127.0.0.1:9876 # name server 地址
  producer:
    group: webook_group
    send-message-timeout: 3000 # 消息发送超时时间，默认 3s
    retry-times-when-send-failed: 3 # 同步发送消息失败后，重试的次数
    retry-times-when-send-async-failed: 3 # 异步发送消息失败后，重试的次数
    max-message-size: 4096 # 消息最大大小
  consumer:
    group: webook_group
    pull-batch-size: 5 # 每次拉取的最大消息数

mq-consumer: # MQ 消费者
  follow-unfollow: # 关注、取关
    rate-limit: 5000 # 每秒限流阈值