server:
  port: 8080 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境
  data:
    redis:
      database: 0 # Redis 数据库索引（默认为 0）
      host: 127.0.0.1 # Redis 服务器地址
      port: 6379 # Redis 服务器连接端口
      password:  # Redis 服务器连接密码（默认为空）
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 链接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 10 # 连接池中的最大空闲连接

mybatis:
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.jacob.micro.auth.domain.mapper: debug

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128
  # 是否输出操作日志
  is-log: true

rate-limit:
  api:
    limit: 100 # 接口限流阈值

alarm:
  type: sms # 告警类型

#nacos:
#  config: # Nacos 配置中心
#    access-key: # 身份验证
#    secret-key: # 身份验证
#    data-id: webook-auth # 指定要加载的配置数据的 Data Id
#    group: DEFAULT_GROUP # 指定配置数据所属的组
#    type: yaml # 指定配置数据的格式
#    server-addr: http://110.41.141.141:8848/ # 指定 Nacos 配置中心的服务器地址
#    auto-refresh: true # 是否自动刷新配置
#    remote-first: true # 是否优先使用远程配置
#    bootstrap:
#      enable: true # 启动时，预热配置