#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================
minio:
  endpoint: http://110.41.141.141:9000
  accessKey: minioadmin
  secretKey: minioadmin